### ISSUE TITLE
How to add a spinner when loading a web page?

### ISSUE THREAD

**Issue by forsigner** [initialxy/cordova-plugin-themeablebrowser#14]
hello~
I have a new issue，how i could add a spinner when loading a web page？

"loadstart" and "loadstop" event work for me，but  when I use [progressindicator](http://ngcordova.com/docs/plugins/progressIndicator/), I could not see spinner,because it is covered by themeablebrowser in background.

**Comment by initialxy** [comment]
I considered adding spinner, however due to the vast variety of ways spinner or progress bar can be added, designing such API is quite challenging. So currently there's no way to add a spinner or loader. One work around I can make at this point is that if your major concern is just the **initial** external page, then you can launch the browser in `hidden` mode then call `show()` when `loadstop` event is emitted. eg.

    var ref = cordova.ThemeableBrowser.open(yourUrl, '_blank', {
        ...
        hidden: true
    });

    // TODO: Show _your_ load spinner on your app however you want
    ref.addEventListener('loadstop', function() {
        // TODO: Dismiss your load spinner.
        ref.show();
    });

As you can see, this will allow the browser to be displayed when the initial page is fully loaded, in the meantime, you can show your own spinner inside your app to stall the user.

**Comment by forsigner** [comment]
thx, I will try it tonight ^ ^

**Comment by mahmud-vir** [comment]
ref.show() not working on ios.
ERROR: Method 'show:' not defined in Plugin 'ThemeableBrowser'

**Comment by initialxy** [comment]
Reference to issue #31
