### ISSUE TITLE
themeablebrowser not opening in android 

### ISSUE THREAD

**Issue by khurramsaddique** [initialxy/cordova-plugin-themeablebrowser#15]
hi its great that you are improving themeablebrowser 
I have an issue in android when i click a link themeablebrowser, its not working eclipse is giving error

<pre>04-30 14:08:27.184: D/SystemWebChromeClient(21575): file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js: Line 25 : No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.</pre>

second log
<pre>
04-30 15:49:08.300: W/InAppChromeClient(23918): ThemeableBrowser does not support Cordova API calls: file:///android_asset/www/contactus.html gap:[0,"ThemeableBrowser","open","ThemeableBrowser1467816280"]

</pre>
```

```
third log when  i execute command --cordova build andriod 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Projects\WMCApp\platforms\android\src\com\initialxy\cordova\themeablebr
owser\ThemeableBrowser.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

```
heres is my code 
 
 <a id="lnkEmail" style="border: none;box-shadow: none;text-align: left;" data-role="button" 
                href="#">
                    support@website.com 
                </a>
 $('#lnkEmail').on('click',function(){ 
      innAppInit('mailto:support@website.com');        
  });  
     app.Log('faqs/contactus link=' + _url);
     if(_target == null || _target == undefined || _target == ''){
        _target = '_blank';
     }
     if (_url == null || _url == '') {
         _url = 'https://www.website.com';
     }
     try {

         var ref = cordova.ThemeableBrowser.open(_url, _target, {
             backButtonCanClose: false,
             disableAnimation: true,
             statusbar: {
                 color: '#239EC9'
             },
             toolbar: {
                 height: 44,
                 color: '#239EC9'
             },
             title: {
                 color: '#FFFFFF',
                 showPageTitle: false,
                 staticText: 'website.com'
             },
             closeButton: {
                 image: 'close',
                 imagePressed: 'close_pressed',
                 align: 'right',
                 event: 'closePressed'
             }
         }).addEventListener(cordova.ThemeableBrowser.EVT_ERR, function(e) {
             if (e.code === cordova.ThemeableBrowser.ERR_CRITICAL) {
                 // TODO: Handle critical error.
             } else if (e.code === cordova.ThemeableBrowser.ERR_LOADFAIL) {
                 // TODO: Image failed to load.
             }
             app.Log('e.code=' + e.code);
             app.Log('e.message=' + e.message);


         }).addEventListener(cordova.ThemeableBrowser.EVT_WRN, function(e) {
             if (e.code === cordova.ThemeableBrowser.WRN_UNDEFINED) {
                 // TODO: Some property undefined in config.
             } else if (e.code === cordova.ThemeableBrowser.WRN_UNEXPECTED) {
                 // TODO: Something strange happened. But no big deal.
             }

             app.Log('e.code=' + e.code);
             app.Log('e.message=' + e.message);
         });;
     } catch (e) {
         app.ErrorLog(e);
     }

     try {
         ref.addEventListener('loadstart', function(event) {

             app.Log('loadstart function');
         });
     } catch (e) {
         app.ErrorLog(e);
     }

     try {
         ref.addEventListener('loadstop', function(event) {
             app.Log('loadstop function');
         });
     } catch (e) {
         app.ErrorLog(e);
     }

     try {
         ref.addEventListener('closePressed', function(event) {
             app.Log('closePressed function');
         });
     } catch (e) {
         app.ErrorLog(e);
     }

 }
```

```
In config.xml i have added whitelist
<plugin name="cordova-plugin-whitelist" version="1" />
    <access origin="*" />
   <allow-intent href="http://*/*" />
   <allow-intent href="https://*/*" />
  <allow-intent href="tel:*" />
  <allow-intent href="sms:*" />
  <allow-intent href="mailto:*" />
   <allow-intent href="geo:*" /> 
```

**Comment by initialxy** [comment]
04-30 14:08:27.184: D/SystemWebChromeClient(21575): file:///android_asset/www/plugins/cordova-plugin-whitelist/whitelist.js: Line 25 : No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.


This is a log message is emitted by [cordova-plugin-whitelist](https://github.com/apache/cordova-plugin-whitelist#content-security-policy). It is an optional feature of cordova-plugin-whitelist, and judging by your use case, you don't need this. So simply ignoring this message will be fine.

    Note: Some input files use or override a deprecated API.

This is expected, since this plugin provides backward compatibility for older versions of Android, so some deprecated APIs are used. Please ignore.

Now here is the most interesting part:

    04-30 15:49:08.300: W/InAppChromeClient(23918): ThemeableBrowser does not support Cordova API calls: file:///android_asset/www/contactus.html gap:[0,"ThemeableBrowser","open","ThemeableBrowser1467816280"]

Judging by this message, I must deduce that you opened a local app file, namely `contactus.html` inside ThemeableBrowser, then from there, you tried to call `cordova.ThemeableBrowser.open`. This does not work by design, in fact, efforts were made to make sure that Cordova plugins cannot be called from inside ThemeableBrowser. The purpose of ThemeableBrowser (as well as [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser)) is to open arbitrary **external** web pages. So think of it this way, if user opened `http://www.probably-some-virus.com` it better not be able to call Cordova Camera API, otherwise people are gonna be mad at you for good reasons.

Therefore I must conclude that this issue is working by design. However given the above observations, I must advice you to rethink how you are redirecting your app with respect to Cordova. Internal app files such as `contactus.html` is most certainly **not** supposed to be opened by ThemeableBrowser, and it should be part of your app navigation. Judging by your sample code, I guess you are using [jQuery Mobile](https://jquerymobile.com/)? In which case, when you navigate to contact us page, instead of opening it in ThemeableBrowser, simply allow it to [redirect with anchor tag](http://demos.jquerymobile.com/1.3.0/docs/examples/redirect/) will do fine.

**Comment by initialxy** [comment]
Another recommendation I'd like to make is that if you open `mailto:*` in ThemeableBrowser, it will prompt the default mail client on your device, which is good. But it will also leave an ugly *Page is not Found* screen inside ThemeableBrowser. I'd recommend you to detect protocol prefix inside your JavaScript code and open `mailto:*` etc directly with `window.open` or `cordova.ThemeableBrowser.open(mailto, '_self')`.
