### ISSUE TITLE
ThemeableBrowser within ThemeableBrowser

### ISSUE THREAD

**Issue by jeewanaryal2012** [initialxy/cordova-plugin-themeablebrowser#18]
I wanted to open this custom browser within the same browser like this:

var ref = cordova.ThemeableBrowser.open(host+url, '_blank', options)
    .addEventListener("myButtonPressed", function(e) {
                      cordova.ThemeableBrowser.open("http://www.google.com", "_blank");
                      });

However, it does not work. Could you please help me to make it work. Or am I missing anything here?

**Comment by initialxy** [comment]
Hi, as per discussion on issue #15, you are not supposed to call any Cordova features while inside ThemeableBrowser. The reason is that ThemeableBrowser as well as [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) are intended to open arbitrary **external** sites, so it would be a security vulnerability if an external site is capable of accessing your device through Cordova. In fact, `cordova.js` shouldn't have been imported at all. So what is recommended is that if a page is internal to your app, then redirect to it inside your app with whatever navigation logic you seem fit, don't open it in ThemeableBrowser. If an external site is opened in ThemeableBrowser, then it should redirect just like it's in any browser (think anchor tag or `window.open`).

**Comment by jeewanaryal2012** [comment]
I was able to resolve this issue. I have a quick question: how can I detect the URL change every time user navigates to different pages within the Theameable Browser. In ChildBrowser, we could use the onlocationchange() method. Is there a similar method here too? I need to read the whole URL string every time there is a changes. Please help me on this.

**Comment by initialxy** [comment]
ThemeableBrowser is forked from [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser), hence it inherits [InAppBrowser's events](https://github.com/apache/cordova-plugin-inappbrowser#addeventlistener) as well. `loadstop` is what you need. eg.

    cordova.ThemeableBrowser.open('http://apache.org', '_blank', {
        ...
    }).addEventListener('loadstop', function(e) {
        alert(e.url);
    });

**Comment by jeewanaryal2012** [comment]
Awesome, thanks man, it's working. You did a great job making this customizable, really helped me a lot. Do you run any blogs or QA kind of sites for your projects?

**Comment by initialxy** [comment]
@jeewanaryal2012, glad I could help. Now that you mentioned it. I do have a crappy blog at [http://www.initialxy.com](http://www.initialxy.com/). But as you can see I got lazy and haven't got back to it in ages.
