### ISSUE TITLE
display CordovaWebView controls on ThemeableBrowser?

### ISSUE THREAD

**Issue by ricolo** [initialxy/cordova-plugin-themeablebrowser#19]
I use the Ionic framework for development with ThemeableBrowser to display external links. If a button on the browser is to trigger an Ionic control (e.g. [action sheet](http://ionicframework.com/docs/api/service/$ionicActionSheet/)), the control would not be visible upon button pressed until the browser is closed. Is there a way to display these CordovaWebView controls on top of the browser, or I have to resort to native controls (with cordova plugins like [this](http://ngcordova.com/docs/plugins/actionSheet/))?

**Comment by initialxy** [comment]
The short answer is, you are right. ThemeableBrowser as well as [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) act more like a native browser on its own, except inside your app instance. So they create their own native layer of WebView/UIWebView (not CordovaWebView) that floats on top of CordovaWebView. While Ionic's directives and services are merely web elements that's inside CordovaWebView and styled to look native. So while ThemeableBrowser is being shown, nothing from the CordovaWebView underneath will become visible, since they are completely separate instances of WebView. (May even be completely different implementations if you factor in [Crosswalk](https://cordova.apache.org/announcements/2015/04/15/cordova-android-4.0.0.html)). However the good news is that despite being covered up, CordovaWebView is still active and can execute JavaScript on its own. So you have to utilize other Cordova plugins that gives you access to **native** widgets, so that they can get on top of ThemeableBrowser.

I can't say what your use case requires. I'd say the easiest course of action is to dismiss ThemeableBrowser first in response to any custom actions, so that the rest of the work flow can return to your app.

**Comment by ricolo** [comment]
I need a few controls that can be triggered in both CordovaWebView and ThemeableBrowser, so it would simplify the structure as well as closely align the look and feel if I can use the same code. Thank you for your explanation and suggestion, to get things to market first I'm more inclined to dismiss the ThemeableBrowser to show the Ionic widgets at this moment, and come back to consider native ones later.
