### ISSUE TITLE
Phonegap build

### ISSUE THREAD

**Issue by gustter** [initialxy/cordova-plugin-themeablebrowser#25]
Hi.

Great job!

I have an issue, I'm using  phonegap build and I don't know how to upload "native images". Any idea?

Thanks.

**Comment by initialxy** [comment]
I'd like to refer you to issue #11, especially the discussion near the bottom. Basically you have to import native images to your project one way or another, and I'd recommend taking advantage of PhoneGap Build's private plugin feature, which is quite simple.

**Comment by gustter** [comment]
Thanks!

Private plugin are for paid accounts. Of course one choice is upgrade but ... 

Is there an alternative to use no image? Characters like < > etc.?

**Comment by gustter** [comment]
Sorry, another question. What if I do not include images, also does not apply the background-color of the bar?

**Comment by initialxy** [comment]
Aw you are right. They make you pay for it. Firstly, let's answer your questions directly. No you can't use characters for buttons. If you don't specify image and background color, button will simply not appear and background color will default to white (`#ffffffff`).

The purpose of this plugin is to find a simple and elegant engineering solution to maximize the flexibility of styling a native component through configuration. So it was built on the assumption that since you are here using ThemeableBrowser instead of [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser), you are looking for maximum freedom in styling your component, instead of looking for some intermediate solution. So using native images was a simple and elegant solution both in config as well as implementation, because supporting multi-density images on native platforms have been there since day 1 and it has very elegant API. I feel breaking away from this solution is over complicating a readily available engineering solution just because the limitations imposed by a third party service, namely, PhoneGap Build.

That being said, I'm willing to look for alternative solutions. However I can't make any promises on delivery nor timeline, since I'm quite busy recently and as you can see, there's a few other high priority issues on the bug tracker. So I marked this issue as enhancement for the moment.

**Comment by initialxy** [comment]
See [experimental features](https://github.com/initialxy/cordova-plugin-themeablebrowser#experimental-properties) available in version 0.2.10, which is already migrated to npm with respect to issue #23, so be sure to use the new ID, `cordova-plugin-themeablebrowser`.

**Comment by gustter** [comment]
Thanks! I'll try and notice.

**Comment by gustter** [comment]
Thanks! You are the one!  Experimental features are perfect!
