### ISSUE TITLE
insertCSS/executeScript option?

### ISSUE THREAD

**Issue by jackyon** [initialxy/cordova-plugin-themeablebrowser#33]
looks like insertCSS/executeScript option were missed?

when I used "loadstop", the alert can be executed, but the insertCSS/executeScript not working, I have the files in the "www" folder.

.addEventListener('loadstop', function() {
        alert('load stop');
        ref.insertCSS({file: "css/style.css"});
        ref.executeScript({file: "js/test.js"});
    });

plz advise!

**Comment by initialxy** [comment]
These two methods were inherited from [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser). I have made no improvements on those so far.

As far as I can tell, file path is relative to the URL you opened, **not** your local `www` directory. So for example if you loaded up `http://apache.org`, `{file: 'js/test.js'}` will actually be linking to `http://apache.org/js/test.js`. In order to link to local files, you have to use the `file:///` protocal. While this is pretty straightforward on Android, unfortunately this does not work well on iOS, where the URL to a local file looks like this `file:///Users/initialxy/Library/Developer/CoreSimulator/Devices/EB775856-C9A6-408D-AC40-31469FF5623B/data/Containers/Bundle/Application/C6A211E9-F074-4BEA-944A-20839E50F168/Test.app/www/js/test.js`, which is actually device specific. So in order to support loading local files with `executeScript` and `insertCSS` there will need to be some native improvements especially for iOS.

**Comment by jackyon** [comment]
thx! this totally clear for me ;)

**Comment by nylsel** [comment]
can you give an example on how did you used the `{code: ...}` ?
i'm sorry i'm new to ionic ans i can't seem to figure out how to use this `.insertCss({code: ...})`
i'm using it to change the size of the title options
hope you can help me
thanks in advance
