### ISSUE TITLE
Using XDK, fails to compile for Android but compiles for Crosswalk

### ISSUE THREAD

**Issue by NSouth** [initialxy/cordova-plugin-themeablebrowser#36]
I'm fairly new to Cordova, so forgive me if this is trivial.  I was using [themeablebrowser from the Cordova Plugins Registry](http://plugins.cordova.io/#/package/com.initialxy.cordova.themeablebrowser) and it seemed to work, but I couldn't figure out how to access native images (and maybe I can't, since builds occur on Intel's servers).  I decided to try the new wwwImage feature, but realized the version in the Cordova Plugins is 0.2.7.  So, I added your plugin straight from github. For whatever reason, builds to Crosswalk for Android work, but Android builds do not. I get these errors.

> -compile:
    [javac] Compiling 12 source files to .../WebToAppMB/platforms/android/ant-build/classes
    [javac] .../WebToAppMB/platforms/android/src/com/initialxy/cordova/themeablebrowser/ThemeableBrowser.java:985: cannot find symbol
    [javac] symbol  : variable LOLLIPOP
    [javac] location: class android.os.Build.VERSION_CODES
    [javac]             if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
    [javac]                                                            ^
    [javac] .../WebToAppMB/platforms/android/src/com/initialxy/cordova/themeablebrowser/ThemeableBrowser.java:988: getDrawable(int) in android.content.res.Resources cannot be applied to (int,android.content.res.Resources.Theme)
    [javac]                 result = activityRes.getDrawable(id, cordova.getActivity().getTheme());
    [javac]                                     ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: .../WebToAppMB/platforms/android/src/com/initialxy/cordova/themeablebrowser/ThemeableBrowser.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors
BUILD FAILED
/Developer/android-sdk-linux/tools/ant/build.xml:720: The following error occurred while executing this line:
/Developer/android-sdk-linux/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

**Comment by initialxy** [comment]
This is because your build system didn't use the latest Android SDK to build. Though this plugin supports Android 4.0 and above, but will need to be built with Android 5.0 and above SDK. In Android, the general practice is to always build with latest SDK, but provide backward compatibility with older API.

**Comment by initialxy** [comment]
I took a look at Intel XDK documentation. They may not have used Android SDK 21+ for building Cordova, which is why you are using this error. At this point, this is pretty behind. But they seem to have updated their CrossWalk build up to date, which is cool. I'd recommend either wait and hope Intel will eventually update their Cordova build or simply use CrossWalk, which I'm personally a fan of.

**Comment by NSouth** [comment]
@initialxy, I think you may be right. My target API is 22, but I just noticed the build log says earlier on that it was trying to build with 19. I'm asking Intel about this now. Thanks for the help.
