### ISSUE TITLE
opening new window in themeablebrowser

### ISSUE THREAD

**Issue by ricolo** [initialxy/cordova-plugin-themeablebrowser#41]
When a webpage triggers window.open() inside the themeablebrowser, a new pop up window is opened. However, there are two issues here:
1. the new window cannot be loaded properly (it should have an image, but only some text is visible)
2. I cannot go back to the previous page

I tried to look for solution here or in cordova's InAppBrowser, but couldn't find anyone raising this issue. Does anyone have experience how this can be handled? Thanks!

**Comment by initialxy** [comment]
I can't picture your issue. Could you please post a screenshot? Also what platform (iOS, Android) and platform versions do you find this issue? Thanks.

**Comment by ricolo** [comment]
Sorry Mr Yu, I should have tested it thoroughly first. The second issue (cannot go back to the previous page) is invalid, while the first issue (new window cannot be loaded properly) only happens for one specific website's opening of new window. Here's the [link](http://www.mpfinance.com/htm/finance/20150805/columnist/afb_afb.htm) to one of this website's articles.

When I click the image (pointed by the green arrow) on this page:

 ![page](https://cloud.githubusercontent.com/assets/1523360/9112790/707bf3d8-3c83-11e5-91bd-6b895bda165c.png)

A new window inside the themeablebrowser is opened like the following screen, which could not show the image as it should be in a normal browser (e.g. iOS Safari):

![screen](https://cloud.githubusercontent.com/assets/1523360/9112838/d0eb4520-3c83-11e5-9d10-38345ac98cce.png)



I suspect the root cause could be in the window.open() parameters this website uses. The image (pointed to by green arrow in the above screenshot) is wrapped within an HTML "a" tag calling the following javascript function:

```
function viewlargephoto(LargePhotoLink)
{
	document.popuplargephoto.PhotoLink.value=LargePhotoLink;
	features='width=300,height=300,resizable=1,scrollbars=1,top=1,left=1,screenX=1,screenY=1';
	window.open('http://www.mpfinance.com/htm/Content_PhotoDisplay.htm','viewlargephoto',features);
}
```

If the window.open() parameter is the root cause, since this is not my website, it seems there is no workaround to properly open this new window in themeablebrowser?

**Comment by initialxy** [comment]
That URL literally gives me a broken image in my desktop Chrome browser. I don't think this is the plugin's probably. More like the website has broken links.
<img width="961" alt="screen shot 2015-08-08 at 4 01 18 pm" src="https://cloud.githubusercontent.com/assets/1842864/9152692/d8684226-3de6-11e5-9b46-13efc0caf2bf.png">

**Comment by initialxy** [comment]
O I see their `window.open` call does some weird stuff. Let me investigate.

**Comment by ricolo** [comment]
Hello @initialxy, do you know a way to work around this issue? I know it's more like that website's problem.

**Comment by initialxy** [comment]
Sorry I've been extremely busy these couple of month. Unfortunately, I don't think there is a work around to this. The reason why this issue occurs is because the popup window refers back to its opener window to retrieve the image URL using JavaScript. This is a rather ancient technique to prevent hot linking that I haven't seen since IE6 days. ThemeableBrowser (as well as InAppBrowser) does not support multiple window mode, so once user navigates away from a window, its previously window is no longer accessible. There seems to be a way to fix this.
http://brainwashinc.com/2014/01/06/ios-uiwebview-handle-window-openwindow-close-popup-page/
But it will take quite some coding and testing on the plugin's side, which I haven't found time lately. If you need this feature urgently, I'd recommend using system browser instead for now.

**Comment by ricolo** [comment]
Thanks @initialxy, I guess better focus on other more useful enhancements instead of work around this kind of dated issue. Let me close this issue.
